version: "3"
services:
  stunnel:
    image: dweomer/stunnel
    environment:
      - STUNNEL_CLIENT: yes
      - STUNNEL_ACCEPT: 0.0.0.0:3800
      - STUNNEL_CONNECT: smpp.marketolog.mts.ru:3800
      - STUNNEL_SERVICE: smpp

    ports:
      - "3801:3800"
    restart: unless-stopped
